### ISSUE TITLE
需要移除对 underscore.string 的依赖

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/underscore-template#9]
作为一个独立项目，外部依赖当然越小越好。

引入 underscore.string 是为了处理字符串，用的最多的是它的 `.trim()` 和 `.include()` API。这两者可以很容易地自己实现。

为了处理 Jedi 在 `<script>` 标签内加的一层注释，又用到了 `.startsWith()` 和 `.endsWith()`。自己实现也不难。希望 Jedi 2.0 出来以后可以完全去掉内部的 `_stripCommentTag()` 方法。

**Comment by zpbx** [comment]
PR #12 已初步完成。
